### ISSUE TITLE
Add support for Heroku-20

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-geo-buildpack#13]
We'll soon want support for Heroku-20. The docker image is available now at `heroku/heroku:20-build`.

**Comment by edmorley** [comment]
Heroku-20 is now in beta:
https://devcenter.heroku.com/changelog-items/1937

@KevinBrolly I took a quick look at the repo to see how the binaries are generated, but I couldn't find the steps to run to call the scripts in the right way. I don't suppose you'd mind taking this one? Just don't want to mess it up! :-)

**Comment by KevinBrolly** [comment]
Added in #14 - Thanks @edmorley !

**Comment by edmorley** [comment]
@KevinBrolly Awesome, thank you :-)

**Comment by lnagel** [comment]
Big thanks!
