### ISSUE TITLE
Use cache busting to ensure apt-get update runs correctly

### ISSUE THREAD

**Issue by thclark** [heroku/heroku-geo-buildpack#3]
I'll leave this to the maintainers in case there's a reason for it I haven't seen; but I believe
`apt-get update ` and `apt-get install` should be on the same line (in the dockerfile [here](https://github.com/heroku/heroku-geo-buildpack/blob/8bcbb1f25515222881efc2805a65781c6b5dad7b/builds/Dockerfile-heroku-18#L3)), based on the [best practices from docker](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) (scroll down to 'APT-GET' section).

**Comment by KevinBrolly** [comment]
Hey @thclark - I found a direct link to the recommendations - https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get

I have made this change now, thanks for another great suggestion!
