### ISSUE TITLE
ERROR 4: Unable to open EPSG support file gcs.csv. Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.

### ISSUE THREAD

**Issue by jimmy-feng** [heroku/heroku-geo-buildpack#40]
Hi all,

I was wondering if anyone could lend any insight and/or provide any help with an issue I'm facing, which was previously asked two years ago (https://github.com/heroku/heroku-geo-buildpack/issues/5) but I can't quite follow the follow-up responses:

![image](https://user-images.githubusercontent.com/52459230/170805663-f195699f-af7d-46df-a544-f04c2b008a61.png)

I thought adding a Config Var: GDAL_DATA = /app/.heroku-geo-buildpack/vendor/share/gdal would solve the issue but it didn't. I retrieved this filepath from line 91 in the following doc: https://github.com/heroku/heroku-geo-buildpack/blob/master/bin/compile

I'm new to heroku so any help would be greatly appreciated! Thank you.

**Comment by edmorley** [comment]
@jimmy-feng Hi! The buildpack sets the environment variable `GDAL_DATA` for you, so there should not be a need to set it manually, unless something is going wrong (in which case we can see about fixing it in the buildpack).

Could you provide the steps to reproduce this issue?

I don't personally use any of the libraries provided by this buildpack, so trying to test anything is hard.

**Comment by jimmy-feng** [comment]
@edmorley Thank ya so much! I set the GDAL_VERSION to 2.4.2 in my config variables and that solved the issue. I'm not sure why that works since it seems the only packages requiring GDAL need a version >3 (Python: geopandas & movingpandas.)

**Comment by edmorley** [comment]
@jimmy-feng Strange! Well, glad you got it working anyway :-)
