### ISSUE TITLE
Troubles with Heroku 22

### ISSUE THREAD

**Issue by AdrianPardo99** [heroku/heroku-geo-buildpack#42]
I want to change version of GDAL (3.5.0 by default, and I want to set by 2.4.0)

The app is development in Django 

In docker i don't have any trouble, but when I update stack and buildpacks the map doesn't display in heroku.

![image](https://user-images.githubusercontent.com/33945793/187510740-910230c1-b775-4517-a880-839ee972b56d.png)

- Last versión deployment

![image](https://user-images.githubusercontent.com/33945793/187510836-8b2f4d13-01f5-45c2-b68e-59b87a817716.png)

- Same row of database in docker

I have many problems with this because, I don't know how change the current default versión in heroku (The terminal gives me an error of envars and I can't see my map well)

![image](https://user-images.githubusercontent.com/33945793/187511150-2e4e7f9e-5d1f-4cd5-a95e-fdbc7df85a5a.png)

**Comment by edmorley** [comment]
Hi!

I would:
1. Check you have the correct buildpacks set (see `heroku buildpacks`)
2. Check you don't have stray env vars set from older versions of the buildpack (see `heroku config`)
3. Clear the build cache (see https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache)

> I don't know how change the current default versión in heroku

This is covered in the README:
https://github.com/heroku/heroku-geo-buildpack#default-versions

**Comment by AdrianPardo99** [comment]
- $GDAL_LIBRARY_PATH=/app/.heroku-geo-buildpack/vendor/lib/libgdal.so
- $GDAL_VERSION=2.4.2
- $GEOS_LIBRARY_PATH=/app/.heroku-geo-buildpack/vendor/lib/libgeos_c.so

I have the next envars related for this buildpack

I consider change version of 3.5.0 because I have some troubles showing my old maps with polys.

My buildpacks are:

- https://github.com/heroku/heroku-geo-buildpack.git
- heroku/python
- heroku/nodejs

**Comment by edmorley** [comment]
Unset `GDAL_LIBRARY_PATH` and `GEOS_LIBRARY_PATH` -- these env vars should not be set when using this buildpack. The buildpack sets the necessary env vars automatically.

**Comment by edmorley** [comment]
Closing since GitHub issues aren't the best place for tech support (this buildpack is provided as-is; it's not an officially supported buildpack) and I've not seen anything here so far that indicates there is an issue with the buildpack itself, vs an app configuration issue.
