### ISSUE TITLE
Buildpack not working

### ISSUE THREAD

**Issue by weoutfun** [heroku/heroku-geo-buildpack#45]
The buildpack now returns error for every stack.
For example:
`Requested GDAL Version (3.5.0) is not available for this stack (heroku-18)`

I am suspecting that it is a problem with the S3 storage. It is probably no longer active/accessible

**Comment by edmorley** [comment]
The buildpack works for me:

```
$ mkdir testcase && cd $_
$ git init && touch test && git add -A && git commit -m 'Initial commit'
...
$ h create --buildpack https://github.com/heroku/heroku-geo-buildpack
Creating app... done, ⬢ afternoon-refuge-50608
Setting buildpack to https://github.com/heroku/heroku-geo-buildpack... done
https://afternoon-refuge-50608-646c324cc8d9.herokuapp.com/ | https://git.heroku.com/afternoon-refuge-50608.git
$ git push heroku main
...
remote: -----> Building on the Heroku-22 stack
remote: -----> Using buildpack: https://github.com/heroku/heroku-geo-buildpack
remote: -----> Geo Packages (GDAL/GEOS/PROJ) app detected
remote: -----> Installing GDAL-3.5.0
remote: -----> Installing GEOS-3.10.2
remote: -----> Installing PROJ-8.2.1
remote: -----> Discovering process types
remote:        Procfile declares types -> (none)
remote:
remote: -----> Compressing...
remote:        Done: 22.3M
remote: -----> Launching...
remote:        Released v3
```

From the error message I see you are using Heroku-18. The Heroku-18 stack is EOL and can no longer be used on Heroku:
https://devcenter.heroku.com/changelog-items/2583

I presume you are using the Geo buildpack via another means (eg Dokku)? (In the future, including the full build log and any other relevant details like the platform on which it is being run would be helpful.)

If so, you'll need to update to a newer stack (Heroku-20 or Heroku-22).

Lastly, you'll also need the latest version of this buildpack, so that you have:
https://github.com/heroku/heroku-geo-buildpack/commit/c452e7234c3bca7ce1d3a91096e53d8f5a35806d

**Comment by weoutfun** [comment]
Thanks for the timely response!

Indeed I am using Dokku and I have been using the buildpack for a couple of years now and never had an issue except today. I initially had GDAL_VERSION 2.4.2 and thought that was the issue but switching to 3.5.0 raises the same error. Here's the build log:

```
-----> Building reservations from herokuish
-----> Adding BUILD_ENV to build environment...
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
       Detected buildpacks: multi python
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-geo-buildpack.git
=====> Detected Framework: Geo Packages (GDAL/GEOS/PROJ)
-----> Installing GDAL-3.5.0
       !     Requested GDAL Version (3.5.0) is not available for this stack (heroku-18).
       !     See: https://github.com/heroku/heroku-geo-buildpack#available-versions
       !     Aborting.
```
I see that there hasn't been an update to the library recently so I am wondering why the build is suddenly not working. My last successful build was about a week ago

**Comment by edmorley** [comment]
The binaries for EOL stacks were removed recently (since they are unused on Heroku, since it's not possible to build on these stacks there), so you will need to update to a newer stack:

> From the error message I see you are using Heroku-18. The Heroku-18 stack is EOL and can no longer be used on Heroku:
> https://devcenter.heroku.com/changelog-items/2583

**Comment by weoutfun** [comment]
I see now. Thanks! 
I have resolved it!

**Comment by edmorley** [comment]
In #46 I've removed the leftover Heroku-18 references in the README to make the lack of Heroku-18 support clearer.
