### ISSUE TITLE
Missing GDAL_DATA environment variable

### ISSUE THREAD

**Issue by thclark** [heroku/heroku-geo-buildpack#5]
When invoking the GDAL library for certain operations, I'm getting:

```
2019-10-11T15:21:20.186674+00:00 app[web.1]: ERROR 2019-10-11 15:21:19,743 libgdal 10 139856534753408 GDAL_ERROR 4: b'Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.'
```

I shelled into an app running this buildpack, and the output of `find . -name "gcs.csv"` is  `./.heroku-geo-buildpack/vendor/share/gdal/gcs.csv`

So, I rebooted my app with the config var:
`GDAL_DATA=/app/.heroku-geo-buildpack/vendor/share/gdal/`
and everything is now hunky dory.

The `heroku/python` buildpack [exports some envvars for gdal](https://github.com/heroku/heroku-buildpack-python/blob/b30838072f31c56c36917d0d2e860d30d46eba78/bin/steps/geo-libs#L47) which provide hints for programs as to where to find GDAL, perhaps `GDAL_DATA` (and other?) envvars should be set in the buildpack?

**Comment by KevinBrolly** [comment]
Hi @thclark - I have updated the buildpack to correctly set the `GDAL_DATA` environment variable as noted in the GDAL build docs this should indeed have been set - https://trac.osgeo.org/gdal/wiki/FAQInstallationAndBuilding#HowtosetGDAL_DATAvariable

Thanks again!
